development:
  host: localhost
  database: atlus_development

test:
  host: localhost
  database: atlus_test

# set these environment variables on your prod server
production:
  host: localhost
  database: test
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
